server:
  port: 9102
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.200.127.120:3306/ih_card_service?useUnicode=true&amp;characterEncoding=UTF-8mb4
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Zwby_test@2019.
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: none
        show_sql: true
eureka:
  instance:
    preferIpAddress: true
    hostname: 101.200.127.120
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://101.200.127.120:1111/eureka/
