server:
  port: 9102
spring:
  data:
    mongodb:
      host: 120.220.207.92
      port: 27017
      username: admin
      password: byh@2020
      database: patient-service
      authentication-database: admin
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/

