server:
  port: 1024
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://123.57.93.190:13507/ih_card_service?useUnicode=true&amp;characterEncoding=UTF-8mb4
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: byh@2019.

    url: jdbc:mysql://120.220.207.91:13507/pushcenter?useUnicode=true&amp;characterEncoding=UTF-8mb4
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Baiyihui@@2018!!



  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: none
        show_sql: true
eureka:
#  instance:
#    hostname: 39.106.13.186
#    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://39.106.13.186:1111/eureka/

#电子健康卡
appId: WwA2hrE7kwUFTMytwRPBLw
termID: zrtestzd

#域名地址
baseCloudUrl: https://devapi.ebaiyihui.com

#航天中心医院url
htzxBaseCloudUrl: http://zryhcs.ebaiyihui.com:9000